
import google.generativeai as genai
import os

def extract_context(chat_text: str):
    api_key = os.environ.get("API_KEY")
    print(api_key)
    if not api_key:
        return "Error: API key not configured."

    genai.configure(api_key=api_key)

    system_prompt = (
        "Extract all important context from the following chat for future reference. "
        "Categorize into technical, creative, research, personal. "
        "Output as a markdown list with category headings."
    )
    combined_prompt = system_prompt + "\n\n" + chat_text

    try:
        model = genai.GenerativeModel('gemini-2.0-flash-lite')
        response = model.generate_content(combined_prompt)
        if response and hasattr(response, 'text'):
            return response.text
        elif hasattr(response, 'candidates'):
            candidate = response.candidates[0]
            return candidate.content.parts.text
        else:
            return "No content was generated by the model."
    except Exception as e:
        return f"An error occurred: {e}"




